name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '24'
      - name: Maven build
        run: ./mvnw --batch-mode --no-transfer-progress verify --file pom.xml jacoco:report -Pjacoco

      - name: Get Maven project version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Test CLI commands
        run: |
          JAR_FILE="./target/plantuml-to-png-${{ steps.get_version.outputs.VERSION }}.jar"
          echo "Testing CLI with $JAR_FILE"
          java -jar $JAR_FILE --help
          # Run basic init commands and check exit code
          java -jar $JAR_FILE --file ./docs/sample-diagram.puml
          echo "✅ CLI commands executed successfully"

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: plantuml-to-png-${{ steps.get_version.outputs.VERSION }}.jar
          path: |
            ./target/plantuml-to-png-${{ steps.get_version.outputs.VERSION }}.jar
